"""empty message

Revision ID: ce4bcf08d575
Revises: 
Create Date: 2024-06-08 10:41:29.348903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4bcf08d575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ud',
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('university', 'department')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['university', 'department'], ['ud.university', 'ud.department'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('video_num', sa.Integer(), nullable=False),
    sa.Column('avg_clarity_rating', sa.Float(), nullable=True),
    sa.Column('avg_interactivity_rating', sa.Float(), nullable=True),
    sa.Column('avg_engagement_rating', sa.Float(), nullable=True),
    sa.Column('avg_correctness_rating', sa.Float(), nullable=True),
    sa.Column('avg_content_depth_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['university', 'department'], ['ud.university', 'ud.department'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('video_num', sa.Integer(), nullable=False),
    sa.Column('avg_clarity_rating', sa.Float(), nullable=True),
    sa.Column('avg_interactivity_rating', sa.Float(), nullable=True),
    sa.Column('avg_engagement_rating', sa.Float(), nullable=True),
    sa.Column('avg_correctness_rating', sa.Float(), nullable=True),
    sa.Column('avg_content_depth_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['university', 'department'], ['ud.university', 'ud.department'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('tc',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id')
    )
    op.create_table('course_plan',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('key_point', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id', 'teacher_id'], ['tc.course_id', 'tc.teacher_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'teacher_id', 'week')
    )
    op.create_table('video',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('upload_account', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=255), nullable=False),
    sa.Column('clarity_rating', sa.Integer(), nullable=True),
    sa.Column('interactivity_rating', sa.Integer(), nullable=True),
    sa.Column('engagement_rating', sa.Integer(), nullable=True),
    sa.Column('correctness_rating', sa.Integer(), nullable=True),
    sa.Column('content_depth_rating', sa.Integer(), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id', 'teacher_id', 'week'], ['course_plan.course_id', 'course_plan.teacher_id', 'course_plan.week'], ),
    sa.ForeignKeyConstraint(['upload_account'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('course_plan')
    op.drop_table('tc')
    op.drop_table('teacher')
    op.drop_table('course')
    op.drop_table('account')
    op.drop_table('ud')
    # ### end Alembic commands ###
